### ISSUE TITLE
Issue with the carousel

### ISSUE THREAD

**Issue by aayushsrivastava9760** [COPS-IITBHU/IG-website#23]
The carousel's chevrons are not well centered with the displayed images.
![issue](https://user-images.githubusercontent.com/81965095/136141145-fbcc9abe-0b39-4681-adc5-7c741930eb25.jpeg)

**Comment by aayushsrivastava9760** [comment]
I am working on this issue. Please assign me this issue.

**Comment by eshaanagarwal** [comment]
@aayushsrivastava9760 Sure ! Go ahead.

**Comment by aayushsrivastava9760** [comment]
@eshaanagarwal  I just want to confirm that I would have to work in the _pages/home.md file rt?

**Comment by aayushsrivastava9760** [comment]
Kindly review my PR.
