### ISSUE TITLE
Fixing Colour Scheme, and Including DarkMode

### ISSUE THREAD

**Issue by Manan-Rathi** [COPS-IITBHU/IG-website#26]
The "People" element on the navbar appears to have a colour mismatch. I want to fix this issue and also fix the typos.

![Screenshot from 2021-10-08 21-11-00](https://user-images.githubusercontent.com/76519771/136585732-5b0d3471-b654-4fa6-9263-6401b6dbb10d.png)

**Comment by hex-plex** [comment]
That's really nice of you to have noticed can I suggest you a better fix... Add dark mode to the website 

Reference: [https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)

use this as reference and implement a button for more reference you can look this up 

[Dark Mode Revisited](https://derekkedziora.com/blog/dark-mode-revisited)

This contains everything tutorial, code and demo.

If you are able to add this it would be really great even if you find some glitches do make a PR we will accept it no matter what. And if it works well we will merge it to master as well

If you are willing I can assign you this

Thanks,
Best Regards

**Comment by Manan-Rathi** [comment]
I'll do it.

**Comment by Manan-Rathi** [comment]
@hex-plex , please review #27
